// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt4Josrfo5ymMCPS01eWkEQWd2nz06s-E',
    appId: '1:344893301051:web:14ae6206bd66895412571e',
    messagingSenderId: '344893301051',
    projectId: 'eduquest-app-5cfdc',
    authDomain: 'eduquest-app-5cfdc.firebaseapp.com',
    storageBucket: 'eduquest-app-5cfdc.firebasestorage.app',
    measurementId: 'G-8BK7FKZBCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3QMxu4Kq58RGfSGa8Exa6RG43ckVWjyw',
    appId: '1:344893301051:android:0fbd00059bdf0e3812571e',
    messagingSenderId: '344893301051',
    projectId: 'eduquest-app-5cfdc',
    storageBucket: 'eduquest-app-5cfdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRX4KCizu2LAsrJ-w_Gni2c-HrLtJSPxA',
    appId: '1:344893301051:ios:40b08bc8a6d8590e12571e',
    messagingSenderId: '344893301051',
    projectId: 'eduquest-app-5cfdc',
    storageBucket: 'eduquest-app-5cfdc.firebasestorage.app',
    androidClientId: '344893301051-tpgav1b65oobhnklpfg8m33givb0vs5u.apps.googleusercontent.com',
    iosClientId: '344893301051-ebd52oi23jp8tbr7ea741m9hi3ene09l.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduquestesay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRX4KCizu2LAsrJ-w_Gni2c-HrLtJSPxA',
    appId: '1:344893301051:ios:40b08bc8a6d8590e12571e',
    messagingSenderId: '344893301051',
    projectId: 'eduquest-app-5cfdc',
    storageBucket: 'eduquest-app-5cfdc.firebasestorage.app',
    androidClientId: '344893301051-tpgav1b65oobhnklpfg8m33givb0vs5u.apps.googleusercontent.com',
    iosClientId: '344893301051-ebd52oi23jp8tbr7ea741m9hi3ene09l.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduquestesay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt4Josrfo5ymMCPS01eWkEQWd2nz06s-E',
    appId: '1:344893301051:web:10ac755e59356c6612571e',
    messagingSenderId: '344893301051',
    projectId: 'eduquest-app-5cfdc',
    authDomain: 'eduquest-app-5cfdc.firebaseapp.com',
    storageBucket: 'eduquest-app-5cfdc.firebasestorage.app',
    measurementId: 'G-Y1QEPEEL2Q',
  );

}